apiVersion: v1
kind: Service
metadata:
  name: db-product-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: db-product
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432