apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres
spec:
  containers:
    - name: postgres-pod
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: '123456'
      ports:
        #- name: postgres-pod
        - containerPort: 5432