apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: postgres-exporter
  ports:
    - protocol: TCP
      port: 9187
      targetPort: 9187