apiVersion: v1
kind: Pod
metadata:
  name: postgres-exporter-pod
  labels:
    app: postgres-exporter
spec:
  containers:
    - name: postgres-exporter-app-pod
      image: quay.io/prometheuscommunity/postgres-exporter
      env:
        - name: DATA_SOURCE_NAME
          value: "postgresql://postgres:123456@10.111.238.117:5432/postgres?sslmode=disable"