apiVersion: v1
kind: Service
metadata:
  name: product-deployment-nodeport-service
spec:
  type: NodePort
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 8070
      targetPort: 8070
      nodePort: 30010