apiVersion: v1
kind: Service
metadata:
  name: product-nodeport-service
spec:
  type: NodePort
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 8086
      #targetPort: 8086
      nodePort: 30010