apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      name: product-pod
      labels:
        app: product
    spec:
      containers:
        - name: product-app
          image: rodrigofbmattos/product-app:0.1