apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      name: product-pod
      labels:
        app: product
    spec:
      containers:
        - name: product-app
          image: rodrigofbmattos/product-app:0.3
          ports:
            - containerPort: 8086
          livenessProbe:
            httpGet:
              port: 8086
              path: /api/product
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 8086
              path: /api/product
            initialDelaySeconds: 60