apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-persistentvolume
  labels:
    app: prometheus
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    #path: /prometheus-data
    #path: C:/kubernetes/prometheus
    path: /run/desktop/mnt/host/c/kubernetes/persistentvolume