apiVersion: v1
kind: Pod
metadata:
  name: prometheus-pod
  labels:
    app: prometheus
spec:
  containers:
    - name: prometheus-app-pod
      image: prom/prometheus
      args:
        #- '--storage.tsdb.retention=6h'
        - '--storage.tsdb.path=/prometheus'
        - '--config.file=/etc/prometheus/prometheus.yml'
      volumeMounts:
      - name: prometheus-configmap-volume
        mountPath: /etc/prometheus
        #mountPath: /etc/prometheus/prometheus.yml
      - name: prometheus-data-volume
        mountPath: /prometheus
  volumes:
    - name: prometheus-configmap-volume
      configMap:
        # Forneça o nome do ConfigMap que contém os arquivos 
        # que você deseja adicionar ao contêiner
        name: prometheus-configmap
    - name: prometheus-data-volume
      persistentVolumeClaim:
        claimName: prometheus-persistentvolumeclaim
      #emptyDir: { }
      #hostPath:
        #path: /prometheus-data