apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configmap
  labels:
    app: prometheus
data:
  prometheus.yml: |-
    # my global config
    global:
      scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
      # scrape_timeout is set to the global default (10s).
    # Alertmanager configuration
    alerting:
      alertmanagers:
        - static_configs:
            - targets:
              # - alertmanager:9093
    # Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
    rule_files:
    # - "first_rules.yml"
    # - "second_rules.yml"
    # A scrape configuration containing exactly one endpoint to scrape:
    # Here it's Prometheus itself.
    scrape_configs:
      # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
      - job_name: "prometheus"
        static_configs:
          - targets: ["10.111.115.247:9090"]
          #- targets: ["localhost:9090"]
          #- targets: ["prometheus:9090"]
      - job_name: "product"
        metrics_path: "/actuator/prometheus"
        scrape_interval: 3s
        static_configs:
          - targets: ["10.99.226.174:8086"]
        #- targets: ["localhost:8086"]
        # Caso tenha mais de 1 contêiner
        #- targets: ["product-app1:8086", "product-app2:8086"]
      - job_name: "postgres"
        scrape_interval: 3s
        static_configs:
          - targets: ["10.107.112.140:9187"]
          #- targets: ["postgres-exporter:9187"]
          #- targets: ["localhost:9187"]